# cloudbuild.yaml

substitutions:
  _ZONE: asia-south1-a
  _INSTANCE_TEMPLATE_NAME: flask-template
  _MIG_NAME: flask-mig
  _PROJECT_ID: $PROJECT_ID

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/flask-hello-world:$SHORT_SHA',
        '.'
      ]

  # Step 2: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/$PROJECT_ID/flask-hello-world:$SHORT_SHA'
      ]

  # Step 3: Create new instance template with container image
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'compute',
        'instance-templates',
        'create-with-container',
        '${_INSTANCE_TEMPLATE_NAME}-${SHORT_SHA}',
        '--machine-type=e2-micro',
        '--container-image=gcr.io/$PROJECT_ID/flask-hello-world:$SHORT_SHA',
        '--container-restart-policy=always'
      ]

  # Step 4: Set MIG to use the new instance template
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'compute',
        'instance-groups',
        'managed',
        'set-instance-template',
        '${_MIG_NAME}',
        '--zone=${_ZONE}',
        '--template=${_INSTANCE_TEMPLATE_NAME}-${SHORT_SHA}'
      ]

  # Step 5: Start rolling update for zero-downtime deployment
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'compute',
        'instance-groups',
        'managed',
        'rolling-action',
        'start-update',
        '${_MIG_NAME}',
        '--zone=${_ZONE}',
        '--version=template=${_INSTANCE_TEMPLATE_NAME}-${SHORT_SHA}',
        '--max-surge=1',
        '--max-unavailable=0'
      ]

images:
  - 'gcr.io/$PROJECT_ID/flask-hello-world:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
